### ISSUE TITLE
Execute button does nothing

### ISSUE THREAD

**Issue by Pitxi** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#13]
When clicking the Execute button in Swagger, nothing happens, no console output, no packets sent. If i make the query from Postman everything work as expected.

**Comment by CelerityChip** [comment]
I struggled with this as well. In my case, I found that adding [Required] attributes on model properties is what broke Swagger in this way. I don't know if it was anything to do with this plugin. Removing those attributes and implementing my own model validation code (which I needed anyway for complex property validation) resolved it.

**Comment by Morasiu** [comment]
That's unexpected. I will have to check it for sure

**Comment by Morasiu** [comment]
It's working in my Demo project in this repo. How can I reproduce it? Can you provide a code sample for your request model?

![Animation](https://user-images.githubusercontent.com/19236279/167249615-e8478971-982f-40aa-9ff4-30e47c380d73.gif)

**Comment by amimaryan** [comment]
Greetings!  I commented in your source code update, but I will also mention this here:

I have been using this package for a couple months now and it has been a life saver. However, I myself am experiencing the same issue! So I think the issue is when you are defining a **simple type** such as a string, int, decimal, etc etc. along with the [Required] attribute. For example, @Morasiu can you add another Field to this **RequiredProductWrapper** that is a simple type. For example:

```
		[Required]
		public string Name { get; set; }
```

Or even try adding this required string field **Name** within the **Product** model you have defined. (This is actually my specific case where it does NOT work.) Let me know of your findings, since its unfortunate I cannot use the [Required] attribute currently due to this issue.

**Comment by Morasiu** [comment]
Okay, now I can work with it. Will see what I can do

**Comment by amimaryan** [comment]
So wait, @Morasiu were you able to reproduce it finally?  If so that is great to hear!

**Comment by Morasiu** [comment]
I'll check this in my free time. Probably weekend and let you know here

**Comment by Morasiu** [comment]
I was able to reproduce it!

But as far I can see it's a bug with swagger related to this one https://github.com/swagger-api/swagger-ui/issues/6295.

I can recommend **NOT** using `DataAnnotation` for validation (i.e. `[Required]`. Instead use `FluentValidation`. It is an amazing library for validation.

**Comment by Morasiu** [comment]
Just tested it with `FluentValidation`. It works fine!

Just add this to `Startup`

```csharp
services.AddControllers()
	.AddNewtonsoftJson(options => {
		options.SerializerSettings.Converters.Add(new StringEnumConverter());
		options.SerializerSettings.Formatting = Formatting.Indented;
	})
	.AddFluentValidation(f => {
		f.RegisterValidatorsFromAssemblyContaining<ProductValidator>();
		f.ImplicitlyValidateChildProperties = true; // Important! Without this it won't work automatically
	});
services.AddFluentValidationRulesToSwagger();
```

and it will work!

**Comment by amimaryan** [comment]
@Morasiu thank you so much for looking into this on your free time.  I will definitely look into Fluent Validations library as a substitute.  Enjoy the rest of your weekend! :)
