### ISSUE TITLE
Breaking changes in Swashbuckle.AspNetCore 7.0

### ISSUE THREAD

**Issue by pew2000** [Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport#24]
Swashbuckle .AspNetCore 7.0 has a breaking change where the schema properties for forms aren't populated anymore which in turn makes the old form return again.

I guess it is related to the following issue:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3133

**Comment by Morasiu** [comment]
Is it a problem with Swashbuckle or with this library? I'm not sure about that.

**Comment by Morasiu** [comment]
Oh... I think I know what do you mean. I will look into that

**Comment by jgarciadelanoceda** [comment]
I was the one that did the Breaking change and it's not as described in the post, the breaking change is that for MinimalApis that have the WithOpenApi extension method, previously the schema reported could be a AllOf where it did not need to be(because there are simple properties).
So the new behaviour is that instead of AllOf the schema for that scenario could be a simple schema with two properties

**Comment by Morasiu** [comment]
Thank you for the extra insight. It will help for sure!

**Comment by Morasiu** [comment]
It should be fixed in 2.0.0. Reopen issue or create new one if not :)
